#!/usr/bin/env ruby

unless Dir.new(Dir.pwd).entries.include?("script") && Dir.new(Dir.pwd).entries.include?("lib")
  puts "ClinicDB: ERROR: Key monitor daemon must be run from the ClinicDB directory"
  exit
end

require 'lib/security_helpers.rb'

pid_file = "keymond.pid"
if File.exist?(pid_file)
  `rm #{pid_file}`
end

`ps -fe | grep keymond | head -n1 > #{pid_file}`
puts "Key Monitor Daemon started"

last = false
while File.exist?(pid_file)
  key_there = securityKeyPresent?
  if key_there
    if !last
      puts "ClinicDB: Security Key found at #{securityVolumeDirectory}"
    end
    `script/startup password`
  else
    if last
      puts "ClinicDB: Security Key removed.  Shutting down server and encrypting database."
    end
    `script/shutdown`
  end
  
  last = key_there
  sleep 5
end