#!/usr/bin/env ruby

unless Dir.new(Dir.pwd).entries.include?("script") && Dir.new(Dir.pwd).entries.include?("lib")
  puts "ClinicDB: ERROR: Key monitor daemon must be run from the ClinicDB directory"
  exit
end

require 'lib/security_helpers.rb'

db_dir = File.dirname(__FILE__) + '/../db/'
gpg_file = db_dir + "production.gpg"
sqlite_file = db_dir + "production.sqlite3"

pid_file = "keymond.pid"
if File.exist?(pid_file)
  `rm #{pid_file}`
end

`ps -fe | grep keymond | head -n1 > #{pid_file}`
puts "Key Monitor Daemon started"

last = false
while File.exist?(pid_file)
  if securityKeyPresent?
    if File.exist?(gpg_file) || !File.exist?(File.dirname(__FILE__) + '/../log/mongrel.pid')
      puts "ClinicDB: Security Key found at #{securityVolumeDirectory}"
      `script/startup password`
    end
  elsif File.exist?(File.dirname(__FILE__) + '/../log/mongrel.pid')
    puts "ClinicDB: Security Key removed.  Shutting down server and encrypting database."
    `script/shutdown`
  elsif File.exist?(sqlite_file)
    `script/encrypt`
  end
  
  sleep 3
end