#!/usr/bin/env ruby
require 'date.rb'

gpg_file = File.dirname(__FILE__) + '/../db/production.sqlite3'
backup_dir = '/clinicdb_backups/'

unless File.exist?(gpg_file)
  puts "ClinicDB: ERROR: Backup cannot run if encrypted db file is not present"
  exit
end

if File.exist?(backup_dir)
  backup_file = backup_dir + "backup_#{Date.today.strftime('%Y_%m_%d') + Time.now.strftime('_%H_%M_%S')}.sqlite3"
  latest_backup_file = backup_dir + "backup_latest.sqlite"
  puts "ClinicDB: Adding backup: #{backup_file}"

  `cp #{gpg_file} #{backup_file}`
  `cp #{gpg_file} #{latest_backup_file}`
else
  puts "ClinicDB: No backup directory.  Skipping backup task."
end
