#!/usr/bin/env ruby


Dir.chdir("#{File.dirname(__FILE__)}/..")

pid = File.dirname(__FILE__) + '/../log/mongrel.pid'

if File.exist?(pid) 
  `mongrel_rails stop`
  `rm #{pid}`
  `script/make_backup`
  log_file = File.dirname(__FILE__) + '/../log/production.log'
  `rm #{log_file}`
  puts "shutdown script finished"
end