#!/usr/bin/env ruby
require 'date.rb'
require 'optparse'

port = 3000
env = "production"
d = true
svnupdate = false

optparse = OptionParser.new do|opts|
	opts.banner = "Usage: startup.rb [options]"
  
	opts.on( '-e', '--env Environment', 'Sets the environment (default is production)' ) do |e|
		env = e = e.downcase
		env = 'production' if e=='p'
		env = 'development' if e=='d'||e=='dev'
	end

	opts.on( '-p', '--port PORT', 'Sets the port (default is 3000)' ) do |p|
		port = p
	end

	opts.on( '-n', '--nondaemon', '' ) do
		d = false
	end

	opts.on( '-u', '--update', '' ) do
		svnupdate = true
	end

	opts.on( '-h', '--help', 'Display this screen' ) do
    	puts opts
		exit
	end
end

optparse.parse!

Dir.chdir("#{File.dirname(__FILE__)}/..")

unless Dir.new(Dir.pwd).entries.include?("script") && Dir.new(Dir.pwd).entries.include?("lib")
  puts "ClinicDB: ERROR: Server startup script must be run from the ClinicDB directory"
  exit
end

if File.exist?(File.dirname(__FILE__) + '/../log/mongrel.pid')
	puts "Shutting down previous mongrel server"
	`script/shutdown`
end

if svnupdate
	puts "Updating software"
	cmd = "mongrel_rails start #{'-d ' if d}-e #{env} --port #{port}"
	`svn update #{File.dirname(__FILE__) + '/../'}`
end

puts "Starting #{env} server on port #{port}"

`rake environment RAILS_ENV=#{env} db:migrate`
if(File.exist?(File.dirname(__FILE__) + "/../db/#{env}.sqlite3"))
	log_file = "log/log_#{Date.today.strftime('%Y_%m_%d') + Time.now.strftime('_%H_%M_%S')}.log"
	cmd = "mongrel_rails start #{'-d ' if d}-e #{env} --port #{port}"
	`#{cmd}`
end

puts "startup script finished"
